# Generated by Django 4.2.10 on 2024-02-25 04:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
        ('order', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(default='inactive', max_length=10)),
                ('order_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('user.account',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_time_stamp', models.DateTimeField()),
                ('delivered_time_stamp', models.DateTimeField()),
                ('delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryman.deliveryman')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordersummary')),
            ],
        ),
    ]
