# Generated by Django 4.2.10 on 2024-02-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_time_stamp', models.DateTimeField()),
                ('delivered_time_stamp', models.DateTimeField()),
            ],
        ),
    ]
