# Generated by Django 4.2.10 on 2024-02-24 07:46

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodie',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(help_text='Enter phone number', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be of 10 digits.', regex='^\\d{10}$')])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_id', models.CharField(help_text='Enter a name or number of your residence', max_length=30)),
                ('residency', models.CharField(help_text='Enter your society or apartment name', max_length=30)),
                ('street', models.CharField(help_text='Enter your street name', max_length=30)),
                ('area', models.CharField(help_text='Enter your area of city', max_length=30)),
                ('pincode', models.CharField(help_text='Enter your postal code', max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be of 6 digits', regex='^\\d{6}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.foodie')),
            ],
        ),
    ]
