# Generated by Django 4.2.10 on 2024-02-24 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_id', models.CharField(help_text='Enter a name or number of your residence', max_length=30)),
                ('residency', models.CharField(help_text='Enter your society or apartment name', max_length=30)),
                ('street', models.CharField(help_text='Enter your street name', max_length=30)),
                ('area', models.CharField(help_text='Enter your area of city', max_length=30)),
                ('pincode', models.CharField(help_text='Enter your postal code', max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be of 6 digits', regex='^\\d{6}$')])),
            ],
        ),
    ]
