# Generated by Django 4.2.10 on 2024-02-25 04:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodie', '0001_initial'),
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ip', 'In Progress'), ('done', 'Delivered')], default='ip', max_length=50)),
                ('total_price', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
                ('foodie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.foodie')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedTiffin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordersummary')),
                ('tiffin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.tiffin')),
            ],
        ),
    ]
